apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebappdeployment
spec:
  revisionHistoryLimit: 10
  replicas: 6
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mavenwebapp
  template:
    metadata:
      name: mavenwebapppod
      labels:
        app: mavenwebapp
    spec:
      containers:
        - name: mavenwebappcontainer
          image: skulkarni24/myimage_6:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappsvc
spec:
  selector:
    app: mavenwebapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
